// api/setup-db.js

const { neon } = require("@neondatabase/serverless");

module.exports = async function handler(req, res) {
  try {
    if (req.method !== "GET") {
      return res.status(405).json({
        success: false,
        error: "GET method required"
      });
    }

    const databaseUrl =
      process.env.DATABASE_URL ||
      process.env.POSTGRES_URL ||
      process.env.STORAGE_DATABASE_URL ||
      process.env.STORAGE_POSTGRES_URL;

    if (!databaseUrl) {
      return res.status(500).json({
        success: false,
        error: "DATABASE_URL is not configured"
      });
    }

    const sql = neon(databaseUrl);

    // Create table if it doesn't exist
    await sql`
      CREATE TABLE IF NOT EXISTS custom_apis (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        url TEXT NOT NULL,
        method VARCHAR(10) NOT NULL DEFAULT 'GET',
        description TEXT DEFAULT '',
        category TEXT DEFAULT 'Custom',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `;

    // Check current ID column type
    const columnInfo = await sql`
      SELECT
        data_type
      FROM information_schema.columns
      WHERE table_name = 'custom_apis'
        AND column_name = 'id'
      LIMIT 1
    `;

    const currentType =
      columnInfo[0]?.data_type || "";

    // Existing table has TEXT/VARCHAR ID
    if (
      currentType === "text" ||
      currentType === "character varying"
    ) {

      // Make sure all existing IDs are numeric
      const invalidIds = await sql`
        SELECT id
        FROM custom_apis
        WHERE id IS NOT NULL
          AND id !~ '^[0-9]+$'
        LIMIT 10
      `;

      if (invalidIds.length > 0) {
        return res.status(400).json({
          success: false,
          error:
            "Existing custom_apis.id contains non-numeric IDs. Delete/recreate the table or migrate those IDs manually.",
          invalid_ids: invalidIds.map(x => x.id)
        });
      }

      // Remove old default first
      await sql`
        ALTER TABLE custom_apis
        ALTER COLUMN id DROP DEFAULT
      `;

      // Convert text IDs to integer
      await sql`
        ALTER TABLE custom_apis
        ALTER COLUMN id TYPE INTEGER
        USING id::integer
      `;
    }

    // Create sequence
    await sql`
      CREATE SEQUENCE IF NOT EXISTS custom_apis_id_seq
      AS INTEGER
      START WITH 1
      INCREMENT BY 1
    `;

    // Find current highest ID
    const maxResult = await sql`
      SELECT COALESCE(MAX(id), 0) AS max_id
      FROM custom_apis
    `;

    const maxId =
      Number(maxResult[0]?.max_id || 0);

    // Set sequence correctly
    await sql`
      SELECT setval(
        'custom_apis_id_seq',
        ${maxId > 0 ? maxId : 1},
        ${maxId > 0}
      )
    `;

    // Set automatic ID
    await sql`
      ALTER TABLE custom_apis
      ALTER COLUMN id
      SET DEFAULT nextval('custom_apis_id_seq')
    `;

    // Make sequence owned by ID column
    await sql`
      ALTER SEQUENCE custom_apis_id_seq
      OWNED BY custom_apis.id
    `;

    // Index
    await sql`
      CREATE INDEX IF NOT EXISTS
      custom_apis_created_at_idx
      ON custom_apis(created_at DESC)
    `;

    const result = await sql`
      SELECT
        COUNT(*) AS total
      FROM custom_apis
    `;

    return res.status(200).json({
      success: true,
      message: "Database setup completed",
      table: "custom_apis",
      id_type: "integer",
      total_apis: Number(result[0]?.total || 0)
    });

  } catch (error) {

    console.error(
      "Database setup error:",
      error
    );

    return res.status(500).json({
      success: false,
      error:
        error.message ||
        "Database setup failed"
    });
  }
};
